### ISSUE TITLE
Backend Database Implementation

### ISSUE THREAD

**Issue by Tristen-Finley** [Tristen-Finley/402Project#4]
Database features are as follows:

- Account system, login page on app, associate payment info with users.
- Able to store and pull up restaurant menus.
- Probably needs to be implemented with Google Firebase.

**Comment by boostem** [comment]
Added 2 databases. 
One database "sgnet_kotlin" has two tables, one for the categories of food (breakfast, lunch, dinner, dessert, drink) in (1,2,3,4,5) and another table that has the food items themselves with an ID number, price, and what category it belongs to. 

The other database "sgnet_accounts" stores user ID number, email and passwords. At the moment it is plaintext but I will be storing encrypted versions

**Comment by boostem** [comment]
![image](https://user-images.githubusercontent.com/6678958/116801275-427acf00-aad6-11eb-9f6e-bc7315b8f29f.png)

**Comment by boostem** [comment]
![image](https://user-images.githubusercontent.com/6678958/116801283-54f50880-aad6-11eb-9c3c-733809581c1e.png)

![image](https://user-images.githubusercontent.com/6678958/116801288-63432480-aad6-11eb-8360-8637e0015477.png)
